{% set version = "0.1.0" %}

package:
  name: fraggler
  version: {{ version }}

source:
  url: TODO
  sha256: TODO

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
    - matplotlib
    - numpy
    - networkx
    - pandas
    - biopython
    - scipy
    - scikit-learn
    - lmfit
    - panel
    - fire
    - pip
  run:
    - python >=3
    - python >=3
    - matplotlib
    - numpy
    - networkx
    - pandas
    - biopython
    - scipy
    - scikit-learn
    - lmfit
    - panel
    - fire
    
test:
  imports:
    - fraggler
  commands:
    - fraggler analyze --help 2>&1 | cat |  grep "fraggler analyze IN_PATH"

about:
  home: https://github.com/willros/fraggler
  license: MIT
  summary: 'Easy Fragment Analysis in Python'
  license_family: GPL